//! Safe wrappers around Jasmin-generated assembly kernels for `hachi`.
//!
//! This crate is the FFI boundary of the Jasmin integration experiment — the
//! *only* place in the repository where `unsafe` appears. `hachi` itself keeps
//! `#![forbid(unsafe_code)]`, does not depend on this crate, and nothing here
//! is seen by the charon/Aeneas extraction or the Lean proofs.
//!
//! # Trust boundary
//!
//! For each exported kernel, correctness splits into three parts:
//!
//! 1. **Jasmin source → assembly.** Inherited from the Jasmin project: the
//!    instruction semantics of the intrinsics used and the verified Jasmin
//!    compiler. Not re-proved here.
//! 2. **The FFI contract** (symbol name, SysV AMD64 ABI, register-only
//!    arguments, no memory access, required CPU features). Stated per kernel
//!    in the `extern` block below and enforced by the safe wrappers; checked
//!    by the differential tests in `tests/differential.rs`.
//! 3. **Kernel semantics vs. the hachi scalar reference.** Checked by
//!    differential testing only. No Lean axiom states it, and the Lean
//!    development continues to reason about the scalar Rust model exclusively.
//!
//! # FFI assumptions (all kernels)
//!
//! * x86-64 only (enforced at compile time below).
//! * Every kernel is a Jasmin `export fn` taking and returning `reg u64`
//!   values only: no pointers, no memory reads or writes, no globals, no
//!   side effects. Under the SysV AMD64 ABI a call is therefore safe for any
//!   argument values, provided the CPU features the instruction selection
//!   needs are present.
//! * `hachi_jazz_mul_hi_u64` uses `MULX` and therefore requires **BMI2**;
//!   the safe wrapper refuses to call it without that feature.

#![deny(unsafe_op_in_unsafe_fn)]
#![deny(missing_docs)]

#[cfg(not(target_arch = "x86_64"))]
compile_error!(
    "hachi-jazz wraps x86-64 assembly generated by Jasmin; \
     it has no implementation for this target architecture"
);

#[cfg(target_arch = "x86_64")]
extern "C" {
    /// `jazz/mul_hi_u64.jazz`: `(x, y) ↦ ⌊x·y / 2^64⌋` in registers
    /// (`rdi`, `rsi` → `rax`), two instructions, no memory access.
    /// Requires BMI2 (`MULX`).
    fn hachi_jazz_mul_hi_u64(x: u64, y: u64) -> u64;
}

/// Whether the Jasmin kernels of this crate can run on this CPU.
///
/// `std` caches the CPUID result, so calling this on a hot path costs one
/// relaxed atomic load after the first call.
#[must_use]
pub fn available() -> bool {
    std::arch::is_x86_feature_detected!("bmi2")
}

/// The high 64 bits of the unsigned product `x * y`, computed by the
/// Jasmin-generated `MULX` kernel: `⌊x·y / 2^64⌋`.
///
/// This is the quantity `hachi::ntt::aux_reduce` forms as
/// `((x as u128) * (m as u128)) / BARRETT_SCALE`.
///
/// # Panics
///
/// Panics if the CPU lacks BMI2 (see [`available`]). The kernel itself takes
/// register arguments only and touches no memory, so given BMI2 the call is
/// safe for all inputs.
#[must_use]
pub fn mul_hi_u64(x: u64, y: u64) -> u64 {
    assert!(
        available(),
        "hachi-jazz: this CPU lacks BMI2, which the MULX kernel requires"
    );
    // SAFETY: the symbol is defined by jazz/mul_hi_u64.s (assembled into this
    // crate by build.rs) as a SysV AMD64 function of two register arguments
    // with no memory access; BMI2, its only CPU requirement, was just checked.
    unsafe { hachi_jazz_mul_hi_u64(x, y) }
}
