-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [hachi]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace hachi

/-- [cpoly::field::P]
    Source: '/cargo/git/checkouts/aeneascomppoly-27508bae189397f4/583cfaf/cpoly/src/field.rs', lines 56:0-56:16
    Name pattern: [cpoly::field::P]
    Visibility: public -/
@[global_simps, irreducible, rust_const "cpoly::field::P"]
def cpoly.field.P : Std.U64 := 4294967197#u64

/-- [cpoly::field::Fp]
    Source: '/cargo/git/checkouts/aeneascomppoly-27508bae189397f4/583cfaf/cpoly/src/field.rs', lines 72:0-72:13
    Name pattern: [cpoly::field::Fp]
    Visibility: public -/
@[reducible, rust_type "cpoly::field::Fp"]
def cpoly.field.Fp := Std.U64

/-- [cpoly::field::{cpoly::field::Fp}::ZERO]
    Source: '/cargo/git/checkouts/aeneascomppoly-27508bae189397f4/583cfaf/cpoly/src/field.rs', lines 76:4-76:22
    Name pattern: [cpoly::field::{cpoly::field::Fp}::ZERO]
    Visibility: public -/
@[global_simps, irreducible, rust_const
  "cpoly::field::{cpoly::field::Fp}::ZERO"]
def cpoly.field.Fp.ZERO : cpoly.field.Fp := 0#u64

/-- [cpoly::field::{impl core::ops::arith::Add<cpoly::field::Fp, cpoly::field::Fp> for cpoly::field::Fp}::add]:
    Source: '/cargo/git/checkouts/aeneascomppoly-27508bae189397f4/583cfaf/cpoly/src/field.rs', lines 111:4-111:31
    Name pattern: [cpoly::field::{core::ops::arith::Add<cpoly::field::Fp, cpoly::field::Fp, cpoly::field::Fp>}::add]
    Visibility: public -/
@[rust_fun
  "cpoly::field::{core::ops::arith::Add<cpoly::field::Fp, cpoly::field::Fp, cpoly::field::Fp>}::add"]
def cpoly.field.Fp.Insts.CoreOpsArithAddFpFp.add
  (self : cpoly.field.Fp) (rhs : cpoly.field.Fp) : Result cpoly.field.Fp := do
  let i ← self + rhs
  let i1 ← i % cpoly.field.P
  ok i1

/-- [cpoly::field::{impl core::ops::arith::Mul<cpoly::field::Fp, cpoly::field::Fp> for cpoly::field::Fp}::mul]:
    Source: '/cargo/git/checkouts/aeneascomppoly-27508bae189397f4/583cfaf/cpoly/src/field.rs', lines 131:4-131:31
    Name pattern: [cpoly::field::{core::ops::arith::Mul<cpoly::field::Fp, cpoly::field::Fp, cpoly::field::Fp>}::mul]
    Visibility: public -/
@[rust_fun
  "cpoly::field::{core::ops::arith::Mul<cpoly::field::Fp, cpoly::field::Fp, cpoly::field::Fp>}::mul"]
def cpoly.field.Fp.Insts.CoreOpsArithMulFpFp.mul
  (self : cpoly.field.Fp) (rhs : cpoly.field.Fp) : Result cpoly.field.Fp := do
  let i ← self * rhs
  let i1 ← i % cpoly.field.P
  ok i1

/-- [cpoly::field::W]
    Source: '/cargo/git/checkouts/aeneascomppoly-27508bae189397f4/583cfaf/cpoly/src/field.rs', lines 171:0-171:15
    Name pattern: [cpoly::field::W]
    Visibility: public -/
@[global_simps, irreducible, rust_const "cpoly::field::W"]
def cpoly.field.W : cpoly.field.Fp := 2#u64

/-- [cpoly::field::Ext4]
    Source: '/cargo/git/checkouts/aeneascomppoly-27508bae189397f4/583cfaf/cpoly/src/field.rs', lines 185:0-185:15
    Name pattern: [cpoly::field::Ext4]
    Visibility: public -/
@[rust_type "cpoly::field::Ext4"]
structure cpoly.field.Ext4 where
  c0 : cpoly.field.Fp
  c1 : cpoly.field.Fp
  c2 : cpoly.field.Fp
  c3 : cpoly.field.Fp

/-- [cpoly::field::{cpoly::field::Ext4}::ZERO]
    Source: '/cargo/git/checkouts/aeneascomppoly-27508bae189397f4/583cfaf/cpoly/src/field.rs', lines 198:4-198:24
    Name pattern: [cpoly::field::{cpoly::field::Ext4}::ZERO]
    Visibility: public -/
@[global_simps, irreducible, rust_const
  "cpoly::field::{cpoly::field::Ext4}::ZERO"]
def cpoly.field.Ext4.ZERO : cpoly.field.Ext4 :=
  {
    c0 := cpoly.field.Fp.ZERO,
    c1 := cpoly.field.Fp.ZERO,
    c2 := cpoly.field.Fp.ZERO,
    c3 := cpoly.field.Fp.ZERO
  }

/-- [cpoly::field::{impl core::ops::arith::Add<cpoly::field::Ext4, cpoly::field::Ext4> for cpoly::field::Ext4}::add]:
    Source: '/cargo/git/checkouts/aeneascomppoly-27508bae189397f4/583cfaf/cpoly/src/field.rs', lines 268:4-268:35
    Name pattern: [cpoly::field::{core::ops::arith::Add<cpoly::field::Ext4, cpoly::field::Ext4, cpoly::field::Ext4>}::add]
    Visibility: public -/
@[rust_fun
  "cpoly::field::{core::ops::arith::Add<cpoly::field::Ext4, cpoly::field::Ext4, cpoly::field::Ext4>}::add"]
def cpoly.field.Ext4.Insts.CoreOpsArithAddExt4Ext4.add
  (self : cpoly.field.Ext4) (rhs : cpoly.field.Ext4) :
  Result cpoly.field.Ext4
  := do
  let f ← cpoly.field.Fp.Insts.CoreOpsArithAddFpFp.add self.c0 rhs.c0
  let f1 ← cpoly.field.Fp.Insts.CoreOpsArithAddFpFp.add self.c1 rhs.c1
  let f2 ← cpoly.field.Fp.Insts.CoreOpsArithAddFpFp.add self.c2 rhs.c2
  let f3 ← cpoly.field.Fp.Insts.CoreOpsArithAddFpFp.add self.c3 rhs.c3
  ok { c0 := f, c1 := f1, c2 := f2, c3 := f3 }

/-- [cpoly::field::{impl core::ops::arith::Mul<cpoly::field::Ext4, cpoly::field::Ext4> for cpoly::field::Ext4}::mul]:
    Source: '/cargo/git/checkouts/aeneascomppoly-27508bae189397f4/583cfaf/cpoly/src/field.rs', lines 315:4-315:35
    Name pattern: [cpoly::field::{core::ops::arith::Mul<cpoly::field::Ext4, cpoly::field::Ext4, cpoly::field::Ext4>}::mul]
    Visibility: public -/
@[rust_fun
  "cpoly::field::{core::ops::arith::Mul<cpoly::field::Ext4, cpoly::field::Ext4, cpoly::field::Ext4>}::mul"]
def cpoly.field.Ext4.Insts.CoreOpsArithMulExt4Ext4.mul
  (self : cpoly.field.Ext4) (rhs : cpoly.field.Ext4) :
  Result cpoly.field.Ext4
  := do
  let t0 ← cpoly.field.Fp.Insts.CoreOpsArithMulFpFp.mul self.c0 rhs.c0
  let f ← cpoly.field.Fp.Insts.CoreOpsArithMulFpFp.mul self.c0 rhs.c1
  let f1 ← cpoly.field.Fp.Insts.CoreOpsArithMulFpFp.mul self.c1 rhs.c0
  let t1 ← cpoly.field.Fp.Insts.CoreOpsArithAddFpFp.add f f1
  let f2 ← cpoly.field.Fp.Insts.CoreOpsArithMulFpFp.mul self.c0 rhs.c2
  let f3 ← cpoly.field.Fp.Insts.CoreOpsArithMulFpFp.mul self.c1 rhs.c1
  let f4 ← cpoly.field.Fp.Insts.CoreOpsArithAddFpFp.add f2 f3
  let f5 ← cpoly.field.Fp.Insts.CoreOpsArithMulFpFp.mul self.c2 rhs.c0
  let t2 ← cpoly.field.Fp.Insts.CoreOpsArithAddFpFp.add f4 f5
  let f6 ← cpoly.field.Fp.Insts.CoreOpsArithMulFpFp.mul self.c0 rhs.c3
  let f7 ← cpoly.field.Fp.Insts.CoreOpsArithMulFpFp.mul self.c1 rhs.c2
  let f8 ← cpoly.field.Fp.Insts.CoreOpsArithAddFpFp.add f6 f7
  let f9 ← cpoly.field.Fp.Insts.CoreOpsArithMulFpFp.mul self.c2 rhs.c1
  let f10 ← cpoly.field.Fp.Insts.CoreOpsArithAddFpFp.add f8 f9
  let f11 ← cpoly.field.Fp.Insts.CoreOpsArithMulFpFp.mul self.c3 rhs.c0
  let t3 ← cpoly.field.Fp.Insts.CoreOpsArithAddFpFp.add f10 f11
  let f12 ← cpoly.field.Fp.Insts.CoreOpsArithMulFpFp.mul self.c1 rhs.c3
  let f13 ← cpoly.field.Fp.Insts.CoreOpsArithMulFpFp.mul self.c2 rhs.c2
  let f14 ← cpoly.field.Fp.Insts.CoreOpsArithAddFpFp.add f12 f13
  let f15 ← cpoly.field.Fp.Insts.CoreOpsArithMulFpFp.mul self.c3 rhs.c1
  let t4 ← cpoly.field.Fp.Insts.CoreOpsArithAddFpFp.add f14 f15
  let f16 ← cpoly.field.Fp.Insts.CoreOpsArithMulFpFp.mul self.c2 rhs.c3
  let f17 ← cpoly.field.Fp.Insts.CoreOpsArithMulFpFp.mul self.c3 rhs.c2
  let t5 ← cpoly.field.Fp.Insts.CoreOpsArithAddFpFp.add f16 f17
  let t6 ← cpoly.field.Fp.Insts.CoreOpsArithMulFpFp.mul self.c3 rhs.c3
  let f18 ← cpoly.field.Fp.Insts.CoreOpsArithMulFpFp.mul cpoly.field.W t4
  let f19 ← cpoly.field.Fp.Insts.CoreOpsArithAddFpFp.add t0 f18
  let f20 ← cpoly.field.Fp.Insts.CoreOpsArithMulFpFp.mul cpoly.field.W t5
  let f21 ← cpoly.field.Fp.Insts.CoreOpsArithAddFpFp.add t1 f20
  let f22 ← cpoly.field.Fp.Insts.CoreOpsArithMulFpFp.mul cpoly.field.W t6
  let f23 ← cpoly.field.Fp.Insts.CoreOpsArithAddFpFp.add t2 f22
  ok { c0 := f19, c1 := f21, c2 := f23, c3 := t3 }

/-- [hachi::params::Q]
    Source: 'src/params.rs', lines 30:0-30:33
    Visibility: public -/
@[global_simps, irreducible] def params.Q : Std.U64 := 4294967197#u64

/-- [hachi::params::EXT_DEGREE]
    Source: 'src/params.rs', lines 37:0-37:32
    Visibility: public -/
@[global_simps, irreducible] def params.EXT_DEGREE : Std.Usize := 4#usize

/-- [hachi::params::EXT_W]
    Source: 'src/params.rs', lines 43:0-43:25
    Visibility: public -/
@[global_simps, irreducible] def params.EXT_W : Std.U64 := 2#u64

/-- [hachi::params::RING_LOG_DEGREE]
    Source: 'src/params.rs', lines 54:0-54:37
    Visibility: public -/
@[global_simps, irreducible] def params.RING_LOG_DEGREE : Std.Usize := 6#usize

/-- [hachi::params::RING_DEGREE]
    Source: 'src/params.rs', lines 67:0-67:34
    Visibility: public -/
@[global_simps, irreducible] def params.RING_DEGREE : Std.Usize := 64#usize

/-- [hachi::params::GADGET_BASE]
    Source: 'src/params.rs', lines 75:0-75:31
    Visibility: public -/
@[global_simps, irreducible] def params.GADGET_BASE : Std.U64 := 2#u64

/-- [hachi::params::GADGET_DIGITS]
    Source: 'src/params.rs', lines 83:0-83:36
    Visibility: public -/
@[global_simps, irreducible] def params.GADGET_DIGITS : Std.Usize := 32#usize

/-- [hachi::smoke::sum]: loop body 0:
    Source: 'src/smoke.rs', lines 34:4-37:5
    Visibility: public -/
@[rust_loop_body]
def smoke.sum_loop.body
  (v : alloc.vec.Vec cpoly.field.Fp) (acc : cpoly.field.Fp) (i : Std.Usize) :
  Result (ControlFlow (cpoly.field.Fp × Std.Usize) cpoly.field.Fp)
  := do
  let i1 := alloc.vec.Vec.len v
  if i < i1
  then
    let f ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice
        cpoly.field.Fp) v i
    let acc1 ← cpoly.field.Fp.Insts.CoreOpsArithAddFpFp.add acc f
    let i2 ← i + 1#usize
    ok (cont (acc1, i2))
  else ok (done acc)

/-- [hachi::smoke::sum]: loop 0:
    Source: 'src/smoke.rs', lines 34:4-37:5
    Visibility: public -/
@[rust_loop]
def smoke.sum_loop
  (v : alloc.vec.Vec cpoly.field.Fp) (acc : cpoly.field.Fp) (i : Std.Usize) :
  Result cpoly.field.Fp
  := do
  loop
    (fun (acc1, i1) => smoke.sum_loop.body v acc1 i1)
    (acc, i)

/-- [hachi::smoke::sum]:
    Source: 'src/smoke.rs', lines 31:0-39:1
    Visibility: public -/
@[reducible]
def smoke.sum (v : alloc.vec.Vec cpoly.field.Fp) : Result cpoly.field.Fp := do
  smoke.sum_loop v cpoly.field.Fp.ZERO 0#usize

/-- [hachi::smoke::ext_sum_of_products]: loop body 0:
    Source: 'src/smoke.rs', lines 50:4-53:5
    Visibility: public -/
@[rust_loop_body]
def smoke.ext_sum_of_products_loop.body
  (a : alloc.vec.Vec cpoly.field.Ext4) (b : alloc.vec.Vec cpoly.field.Ext4)
  (acc : cpoly.field.Ext4) (i : Std.Usize) :
  Result (ControlFlow (cpoly.field.Ext4 × Std.Usize) cpoly.field.Ext4)
  := do
  let i1 := alloc.vec.Vec.len a
  if i < i1
  then
    let i2 := alloc.vec.Vec.len b
    if i < i2
    then
      let e ←
        alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice
          cpoly.field.Ext4) a i
      let e1 ←
        alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice
          cpoly.field.Ext4) b i
      let e2 ← cpoly.field.Ext4.Insts.CoreOpsArithMulExt4Ext4.mul e e1
      let acc1 ← cpoly.field.Ext4.Insts.CoreOpsArithAddExt4Ext4.add acc e2
      let i3 ← i + 1#usize
      ok (cont (acc1, i3))
    else ok (done acc)
  else ok (done acc)

/-- [hachi::smoke::ext_sum_of_products]: loop 0:
    Source: 'src/smoke.rs', lines 50:4-53:5
    Visibility: public -/
@[rust_loop]
def smoke.ext_sum_of_products_loop
  (a : alloc.vec.Vec cpoly.field.Ext4) (b : alloc.vec.Vec cpoly.field.Ext4)
  (acc : cpoly.field.Ext4) (i : Std.Usize) :
  Result cpoly.field.Ext4
  := do
  loop
    (fun (acc1, i1) => smoke.ext_sum_of_products_loop.body a b acc1 i1)
    (acc, i)

/-- [hachi::smoke::ext_sum_of_products]:
    Source: 'src/smoke.rs', lines 47:0-55:1
    Visibility: public -/
@[reducible]
def smoke.ext_sum_of_products
  (a : alloc.vec.Vec cpoly.field.Ext4) (b : alloc.vec.Vec cpoly.field.Ext4) :
  Result cpoly.field.Ext4
  := do
  smoke.ext_sum_of_products_loop a b cpoly.field.Ext4.ZERO 0#usize

end hachi
